config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'my_threads#index'
  resources :my_threads, except: :show do
    resources :comments, except: :show
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :my_thread
  belongs_to :user
  validates :title, presence: :true
end

app/models/my_thread.rb
class MyThread < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  validates :title, presence: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :my_threads
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_thread, except: [:show, :destroy]

  def index
    @comments = @thread.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.new(title: params.require(:comment)[:title],
                                         my_thread_id: params[:my_thread_id])
    if @comment.save
      redirect_to my_thread_comments_path
    else
      render :new
    end
  end

  def edit
    comment
  end

  def update
    if comment.update(comment_params)
      redirect_to my_thread_comments_path
    else
      render :new
    end
  end

  def destroy
    comment.destroy
    redirect_to my_thread_comments_path
  end

  private

  def set_thread
    @thread = MyThread.find(params[:my_thread_id])
  end

  def comment
    @comment ||= Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:title).merge(my_thread_id: params[:my_thread_id])
  end

end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController

  def index
    @threads = MyThread.all
  end

  def new
    @thread = MyThread.new
  end

  def create
    @thread = current_user.my_threads.new(title: params.require(:my_thread)[:title])
    if @thread.save
      redirect_to my_threads_path
    else
      render :new
    end
  end

  def edit
    thread
  end

  def update
    if thread.update(thread_params)
      redirect_to my_threads_path
    else
      render :new
    end
  end

  def destroy
    thread.destroy
    redirect_to my_threads_path
  end

  private

  def thread
    @thread ||= MyThread.find(params[:id])
  end

  def thread_params
    params.require(:my_thread).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@thread, @comment] do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>コメント編集</h1>

<%= render 'form' %>

<%= link_to '戻る', my_thread_comments_path(@thread) %>

app/views/comments/index.html.erb
<h1>コメント一覧</h1>

<% @comments.each do |comment| %>
  <%= comment.title %>
  <% if comment.user_id == current_user.id %>
    <%= link_to "編集", edit_my_thread_comment_path(@thread,comment) %>
    <%= link_to "削除", "/my_threads/#{@thread.id}/comments/#{comment.id}", method: :delete %>
  <% end %>
  <br>
<% end %>

<br>

<%= link_to '新規コメント', new_my_thread_comment_path %>
<%= link_to 'ホームへ', my_threads_path %>

app/views/comments/new.html.erb
<h1>新規コメント作成</h1>

<%= render 'form' %>

<%= link_to '戻る', my_thread_comments_path(@thread) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/my_threads/_form.html.erb
<%= form_for(@thread) do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/my_threads/edit.html.erb
<h1>スレッド編集</h1>

<%= render 'form' %>

<%= link_to '戻る', my_threads_path %>

app/views/my_threads/index.html.erb
<h1>スレッド一覧</h1>

<% @threads.each do |thread| %>
  <%= link_to thread.title, my_thread_comments_path(thread) %>
  <% if thread.user_id == current_user.id %>
    <%= link_to "編集", edit_my_thread_path(thread) %>
    <%= link_to "削除", "/my_threads/#{thread.id}", method: :delete %>
  <% end %>
  <br>
<% end %>

<br>

<%= link_to '新規スレッド', new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>新規スレッド作成</h1>

<%= render 'form' %>

<%= link_to '戻る', my_threads_path %>